#!/usr/bin/env python3
"""
Generate the plan documents from the same data the site uses, so the docs
can never drift from the app.

  docs/12-week-plan.md
  docs/linkedin-calendar.md

Re-run:  python3 tools/build-docs.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"

WEEK_THEME = {
    1: "Course setup, AWS account hardening, Architecture Decision Record. **No services deployed.**",
    2: "EC2 + user-data, first deployment. IAM and cost control. Exam Prep block.",
    3: "Linux deep dive. Shell, permissions, processes, systemd.",
    4: "Networking (VPC, subnet, routing). Monitoring and Security gap block.",
    5: "Security (IAM, least privilege, encryption). Finish the S3/CloudFront/SSM layer.",
    6: "Python + boto3. Managing Resource Consumption gap block. RDS provisioned.",
    7: "Databases. Secrets Manager wired in. CloudFront + Route 53 + ACM live.",
    8: "Automated and Repeatable Deployments gap block. CloudWatch alarms + GitHub Actions + CloudFormation.",
    9: "AWS Architecture, Systems Operations, Tooling. AI portfolio: write the eval set first.",
    10: "AWS ML and Generative AI gap block. Bedrock + RAG endpoint + eval scorecard.",
    11: "Servers, Scaling, Serverless, AWS Database Services. VulnScan starts. Project write-ups.",
    12: "AWS Networking Services, Storage and Archiving, Exam Prep. Everything shipped.",
}


def load(name):
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def plural(n, word):
    return f"{n} {word}" + ("" if n == 1 else "s")


def build_plan():
    mods = load("modules.json")["modules"]
    days = load("days.json")["days"]
    projects = load("projects.json")

    by_slug = {m["slug"]: m for m in mods}
    weeks = {w: {"days": [], "modules": [], "gaps": [], "miles": []} for w in range(1, 13)}

    for d in days:
        w = d["week"]
        weeks[w]["days"].append(d)
        for slug in d["awsPrimary"]:
            if slug not in weeks[w]["modules"]:
                weeks[w]["modules"].append(slug)
        for slug in d["awsGap"]:
            if slug not in weeks[w]["gaps"]:
                weeks[w]["gaps"].append(slug)

    for p in projects["projects"]:
        for m in p["milestones"]:
            weeks[m["week"]]["miles"].append((p, m))

    L = []
    L.append("# 12-week plan")
    L.append("")
    L.append("> Generated by `tools/build-docs.py`. Edit the data files, not this file.")
    L.append("")
    L.append("60 Generation days at 5 days per week, mapped against all 24 AWS re/Start")
    L.append("modules. Five modules are *not* covered by the Generation schedule and are")
    L.append("scheduled as **gap blocks** in weeks 2, 4, 6, 8 and 10/11.")
    L.append("")
    total_req = sum(m["requiredItems"] for m in mods)
    L.append(f"- AWS required items: **{total_req}**")
    L.append("- Generation items: **%d**" % sum(
        len(d[h]["items"]) for d in days for h in ("am", "pm") if d[h]))
    L.append(f"- Project milestones: **{sum(len(p['milestones']) for p in projects['projects'])}**")
    L.append(f"- LinkedIn posts: **{sum(len(w['posts']) for w in load('linkedin.json')['weeks'])}**")
    L.append("")

    L.append("## Gap modules")
    L.append("")
    L.append("| Module | Items | Scheduled |")
    L.append("|---|---:|---|")
    for m in mods:
        if not m["isGap"]:
            continue
        when = "week %s" % m["weekTarget"]
        L.append(f"| {m['name']} | {m['itemCount']} | {when} |")
    L.append("")

    for w in range(1, 13):
        wd = weeks[w]
        L.append(f"## Week {w}")
        L.append("")
        L.append(f"**Theme.** {WEEK_THEME[w]}")
        L.append("")
        L.append(f"**Program days.** {wd['days'][0]['day']}-{wd['days'][-1]['day']}")
        L.append("")
        if wd["modules"]:
            L.append("**AWS re/Start modules.**")
            L.append("")
            for slug in wd["modules"]:
                m = by_slug[slug]
                req = (f"{plural(m['itemCount'], 'item')}, all required" if m["requirement"] == "all"
                       else f"{plural(m['itemCount'], 'item')}, complete one" if m["requirement"] == "one"
                       else f"{plural(m['itemCount'], 'item')}, no requirement")
                L.append(f"- {m['name']} &mdash; {req}")
            L.append("")
        if wd["gaps"]:
            L.append("**Gap block.**")
            L.append("")
            for slug in wd["gaps"]:
                m = by_slug[slug]
                L.append(f"- {m['name']} &mdash; {plural(m['itemCount'], 'item')}, all required")
            L.append("")
        if wd["miles"]:
            L.append("**Project milestones.**")
            L.append("")
            for p, m in sorted(wd["miles"], key=lambda x: x[1]["id"]):
                L.append(f"- *{p['name']}* &mdash; {m['title']}: {m['detail']}")
            L.append("")
        L.append("| Day | AM | PM | AWS target | Gap block |")
        L.append("|---:|---:|---:|---|---|")
        for d in wd["days"]:
            am = d["am"]["itemCount"] if d["am"] else 0
            pm = d["pm"]["itemCount"] if d["pm"] else 0
            primary = ", ".join(by_slug[s]["name"] for s in d["awsPrimary"]) or "&mdash;"
            gap = ", ".join(by_slug[s]["name"] for s in d["awsGap"]) or ""
            L.append(f"| {d['day']} | {am} | {pm} | {primary} | {gap} |")
        L.append("")

    return "\n".join(L) + "\n"


def build_calendar():
    li = load("linkedin.json")
    L = []
    L.append("# LinkedIn calendar")
    L.append("")
    L.append("> Generated by `tools/build-docs.py`. Edit `data/linkedin.json`.")
    L.append("")
    L.append(f"**{li['cadence']}**")
    L.append("")
    L.append("## Non-negotiable rules")
    L.append("")
    for r in li["rules"]:
        L.append(f"- {r}")
    L.append("")
    L.append("## Post format")
    L.append("")
    for i, f in enumerate(li["format"], 1):
        L.append(f"{i}. {f}")
    L.append("")

    for w in li["weeks"]:
        L.append(f"## Week {w['week']}")
        L.append("")
        for p in w["posts"]:
            kind = "project" if p["type"] == "project" else "course"
            L.append(f"### {p['id']} &mdash; {kind}")
            L.append("")
            L.append(f"**Hook.** {p['hook']}")
            L.append("")
            L.append(f"**Evidence.** {p['evidence']}")
            L.append("")
            L.append("**Checklist before publishing**")
            L.append("")
            L.append("- [ ] Attach a screenshot, diagram, code block, or live link")
            L.append("- [ ] Contains one concrete number, mistake, or result")
            L.append("- [ ] Ends with a question that invites a real answer")
            L.append("- [ ] No post ships without the artifact")
            L.append("")

    return "\n".join(L) + "\n"


def main():
    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / "12-week-plan.md").write_text(build_plan(), encoding="utf-8")
    (DOCS / "linkedin-calendar.md").write_text(build_calendar(), encoding="utf-8")
    print("docs/12-week-plan.md")
    print("docs/linkedin-calendar.md")


if __name__ == "__main__":
    main()
